### PR TITLE
Add insert/replace

### PR DESCRIPTION
**Pull request by alexispires**
What this pull request adds:
- Gives the possibility to insert a rule (until now only possible by giving a position).
- Gives the possibility to give a position when adding (not only with insert) a rule.
- Rearrangement of netlink messages (Handle block) to allow testing.

To do that:
- 2 new functions : InsertRule and ReplaceRule

Breaking changes:
- You can't insert a rule at a given position with ``AddRule`` anymore
- You can't replace a rule with ``AddRule`` anymore

### CODE REVIEW

**Comment by sbezverk** [comment]
@alexispires this is breaking change, it is going to be @stapelberg call, but I am not sure it is worth it, especially since you can do already Insert with existing AddRule. If you want to Insert a rule, you specify existing and valid rule handle, then AddRule behaves as Insert, if you do not specify rule handle, then AddRule will append a new rule. Personally I do not think it is worth to break existing API.

**Comment by stapelberg** [comment]
> this is breaking change

In which way? It looks purely additive to me?

**Comment by alexispires** [comment]
According to this https://wiki.nftables.org/wiki-nftables/index.php/Simple_rule_management with ``nft`` we can:

| Kind | Position/Handle | No Position/Handle |
| --- | --- | --- |
| Add | Yes : add after rule | Yes : add at the end | 
| Insert | Yes : add before rule | Yes : add at the beginning | 
| Replace | Yes | No |

With the current code:

| Kind | Position/Handle | No Position/Handle |
| --- | --- | --- |
| Add | No | Yes : add at the end | 
| Insert | Yes : add before rule | No | 
| Replace | Yes | No |

Another problem is that the ``AddRule`` function is used for all cases. For me if I do an add rule with a position I expect that, as with ``nft``, the rule is added after and not before. Currently there is no add / insert distinction.

Breaking changes:
- You can't insert a rule at a given position with ``AddRule`` anymore
- You can't replace a rule with ``AddRule`` anymore

**Comment by stapelberg** [comment]
> Breaking changes:
> 
> * You can't insert a rule at a given position with `AddRule` anymore
> * You can't replace a rule with `AddRule` anymore

Can the code be modified such that the old behavior is retained without losing any of the new behavior?

**Comment by alexispires** [comment]
> > Breaking changes:
> > 
> > * You can't insert a rule at a given position with `AddRule` anymore
> > * You can't replace a rule with `AddRule` anymore
> 
> Can the code be modified such that the old behavior is retained without losing any of the new behavior?

I think it might make the code dirty, but:
> You can't insert a rule at a given position with AddRule anymore

We can't keep the old behavior because it's wrong. This PR allow to add after a rule, the current code add before. If i keep it, i loose the ability to add after a rule.

> You can't replace a rule with AddRule anymore

It's possible like this: if an handle value is set so it's a replace operation. The counterpart is that we can make a replacement operation with AddRule, InsertRule and ReplaceRule. It's weird but ok.

**Comment by alexispires** [comment]
For the second breaking change:

```diff
diff --git a/rule.go b/rule.go
index 505e327..a86ce97 100644
--- a/rule.go
+++ b/rule.go
@@ -158,10 +158,18 @@ func (cc *Conn) ReplaceRule(r *Rule) *Rule {
 }
 
 func (cc *Conn) AddRule(r *Rule) *Rule {
+       if r.Handle != 0 {
+               return cc.newRule(r, operationReplace)
+       }
+
        return cc.newRule(r, operationAdd)
 }
 
 func (cc *Conn) InsertRule(r *Rule) *Rule {
+       if r.Handle != 0 {
+               return cc.newRule(r, operationReplace)
+       }
+
        return cc.newRule(r, operationInsert)
 }
 

```

**Comment by sbezverk** [comment]
In general in networking `replace` function it is asking for troubles, as it may leave your system in a indeterministic condition if replacement fails. Using `make before break` is much safer option and it minimizes possibility of a traffic drop. In the code I do `AddRule with insert` which inserts a new rule before the old one and if operation is successful, only then delete the old rule.

**Comment by alexispires** [comment]
I'm not sure we understand each other. I'm not trying to implement a userland replace operation, but to use the nftables API to do so (by using ``NLM_F_REPLACE`` flag).

Same with insert. If you look sendmsg with strace you can see that the difference between insert and add (with ``nft`` userland bin) is the presence of ``NLM_F_APPEND`` flag.

**Comment by alexispires** [comment]
I added more test cases (on header flags) but we should consider doing refactoring. The nftables_test.go file is more than 4000 lines long.

**Comment by stapelberg** [comment]
> We can't keep the old behavior because it's wrong. This PR allow to add after a rule, the current code add before. If i keep it, i loose the ability to add after a rule. Note that we can still add before a rule with the new `InsertRule` function.

Fair enough. @sbezverk, are you relying on the current behavior? Can you prepare a PR in your project to switch to the new behavior if yes? I’d like to (eventually) merge this change.

> For the second breaking change:
> 
> ```diff
> diff --git a/rule.go b/rule.go
> index 505e327..a86ce97 100644
> --- a/rule.go
> +++ b/rule.go
> @@ -158,10 +158,18 @@ func (cc *Conn) ReplaceRule(r *Rule) *Rule {
>  }
>  
>  func (cc *Conn) AddRule(r *Rule) *Rule {
> +       if r.Handle != 0 {
> +               return cc.newRule(r, operationReplace)
> +       }
> +
>         return cc.newRule(r, operationAdd)
>  }
>  
>  func (cc *Conn) InsertRule(r *Rule) *Rule {
> +       if r.Handle != 0 {
> +               return cc.newRule(r, operationReplace)
> +       }
> +
>         return cc.newRule(r, operationInsert)
>  }
>  
> ```

This looks good to me, can you update the PR please?

> I added more test cases (on header flags) but we should consider doing refactoring. The nftables_test.go file is more than 4000 lines long.

Agreed, but that should happen in a separate PR.

> In general in networking `replace` function it is asking for troubles, as it may leave your system in a indeterministic condition if replacement fails.

I thought one of the big improvements that nftables brings over iptables is that it allows for atomic rule replacement? See https://wiki.nftables.org/wiki-nftables/index.php/Atomic_rule_replacement

**Comment by alexispires** [comment]
@stapelberg done

**Comment by sbezverk** [comment]
@stapelberg @alexispires with these 2 wrappers it will work for me too.

> I thought one of the big improvements that nftables brings over iptables is that it allows for atomic rule replacement? See https://wiki.nftables.org/wiki-nftables/index.php/Atomic_rule_replacement

unless  I am missing something it talks mostly about `nft` cli tool,  and not much about atomic in api and whether rule replace api call is truly atomic. It is possible, but from brief check of the page I did not find this confirmation.

**Comment by alexispires** [comment]
I added live kernel tests for all cases: 
- Insert with position
- Insert at beggining
- add with position
- add at the end
- replace with handle

**Pull request merged**
