### PR TITLE
res_id is big endian

### PR DESCRIPTION
**Pull request by florianl**
Signed-off-by: Lehner Florian <dev@der-flo.net>

According to include/uapi/linux/netfilter/nfnetlink.h res_id in nfgenmsg is Big Endian.

### CODE REVIEW

**Comment by stapelberg** [comment]
Thanks for the PR!

I’ll give this a spin later today. In the meantime, could you squash your commits into a single, logical commit please?

**Comment by stapelberg** [comment]
Thanks again.

Out of curiosity, are you using this package for a project? Anything you can share? :)

**Comment by florianl** [comment]
This PR is more a result of debugging an issue for github.com/florianl/go-nflog. There, I faced the same issue.

**Comment by stapelberg** [comment]
Oh! I’m glad the code comes in useful to build other packages, and that you care enough to contribute fixes :)

Thank you!

**Pull request merged**
