### PR TITLE
Add logic for regular chains

### PR DESCRIPTION
**Pull request by sbezverk**
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>
Closes: #27 

With this PR I was able to create these chains and jump:
```
<pre>table ip ipv4table {
	set ipv4rule-1 {
		type inet_service
		flags constant
		elements = { 12000 }
	}

	chain ipv4chain-1 {
		type filter hook input priority 0; policy accept;
		tcp dport @ipv4rule-1 jump ipv4chain-3
	}

	chain ipv4chain-2 {
	}

	chain ipv4chain-3 {
	}
```

### CODE REVIEW

**Comment by sbezverk** [comment]
@stapelberg PTAL

**Comment by sbezverk** [comment]
@stapelberg any chance you could review it? it is a bit of a stopper for me. Thanks a lot..

**Comment by stapelberg** [comment]
Looks simple enough, but could you also send a test which verifies this change works correctly please?

**Comment by sbezverk** [comment]
@stapelberg thanks so much, will add unit test in follow up PR

**Comment by sbezverk** [comment]
@stapelberg I am trying to get byte sequence for nft chain add for unit test. By some reason `sendto` call is abbreviated.
I am using this command to get the sequence:
```
sudo strace -f -v -x -s 2048 -eraw=sendto nft add chain ip filter base-chain { type filter hook prerouting priority 0 \; }
```
Anything I am doing wrong? Strangely for `nft add table` I can clearly see byte sequence.

**Comment by stapelberg** [comment]
Which version of strace are you using? You might be running into https://github.com/strace/strace/issues/100

**Pull request merged**
