### PR TITLE
Implement flush functions

### PR DESCRIPTION
**Pull request by Minaru**
- Add flush functions for Table, Chain and Set
- Add test case for each new function

### CODE REVIEW

**Comment by Minaru** [comment]
Will have to look at what's wrong as it works when I `go test` locally.

**Comment by Minaru** [comment]
After investigating a bit, I found something very weird:

This [function](https://github.com/google/nftables/blob/master/rule.go#L41) which is supposed to return me a list of pointers to rules contained in a given chain actually returns me all the rules contained by any chain in the table given as argument. 

When printing the table/chain of each rule in the travis build, I end up with this [output](https://travis-ci.org/google/nftables/builds/601905480#L561):

```
=== RUN   TestFlushTable

--- FAIL: TestFlushTable (0.11s)

	nftables_test.go:1949: len(rules) = 4, want 2

		Rules are {Name:filter Use:0 Flags:0 Family:0} {Name:forward Table:<nil> Hooknum:0 Priority:0 Type: Policy:<nil>} {Name:filter Use:0 Flags:0 Family:0} {Name:forward Table:<nil> Hooknum:0 Priority:0 Type: Policy:<nil>} {Name:filter Use:0 Flags:0 Family:0} {Name:input Table:<nil> Hooknum:0 Priority:0 Type: Policy:<nil>} {Name:nat Use:0 Flags:0 Family:0} {Name:prerouting Table:<nil> Hooknum:0 Priority:0 Type: Policy:<nil>}
```
with the call `c.GetRule(filter, forward)`

Am I using GetRule the wrong way ? Or is there an issue with that function ?

**Comment by stapelberg** [comment]
This PR works on my machine, too.

Travis is running these tests on 4.4.0-101-generic (Ubuntu 14.04 trusty). You could run Ubuntu 14.04 in a VM and see if the issue is reproducible there. If so, perhaps it’s a kernel issue that was fixed later?

If that turns out to be true, you can check the kernel version and t.Skip the test if the detected kernel is too old.

**Comment by Minaru** [comment]
I was suspicious about the kernel version as well as mine is a 4.14.141-1-MANJARO, just wasn't sure as my research were going in all directions at the same time.

I got a look at libnftnl and it seems they added the individual flushes later on (didn't check for GetRule), only flush ruleset was available for a while. I'm not sure about the kernel module itself as I have little to not experience when it comes to that, making my searches ineffective.

I'll try to get an Ubuntu 14.04 VM running for now, will keep you up to date on that part. In case it's a kernel version issue, how could we find in which version the fix has been implemented ? That way we can add in the godoc "Only works with kernel version above x.x.x".

**Comment by Minaru** [comment]
Test:
```
root@ubuntu:~/go/src/github.com/google/nftables# ./nftables.test -test.v -run_system_tests
=== RUN   TestConfigureNAT
--- PASS: TestConfigureNAT (0.00s)
=== RUN   TestConfigureNATSourceAddress
--- PASS: TestConfigureNATSourceAddress (0.00s)
=== RUN   TestGetRule
--- PASS: TestGetRule (0.00s)
=== RUN   TestAddCounter
--- PASS: TestAddCounter (0.00s)
=== RUN   TestDelRule
--- PASS: TestDelRule (0.00s)
=== RUN   TestLog
--- PASS: TestLog (0.00s)
=== RUN   TestTProxy
--- PASS: TestTProxy (0.00s)
=== RUN   TestCt
--- PASS: TestCt (0.00s)
=== RUN   TestCtSet
--- PASS: TestCtSet (0.00s)
=== RUN   TestAddRuleWithPosition
--- PASS: TestAddRuleWithPosition (0.00s)
=== RUN   TestAddChain
--- PASS: TestAddChain (0.00s)
=== RUN   TestDelChain
--- PASS: TestDelChain (0.00s)
=== RUN   TestGetObjReset
--- PASS: TestGetObjReset (0.00s)
=== RUN   TestConfigureClamping
--- PASS: TestConfigureClamping (0.00s)
=== RUN   TestDropVerdict
--- PASS: TestDropVerdict (0.00s)
=== RUN   TestCreateUseAnonymousSet
--- PASS: TestCreateUseAnonymousSet (0.00s)
=== RUN   TestCreateUseNamedSet
Discover set kek
Discover set IPs_4_dayz
--- PASS: TestCreateUseNamedSet (0.00s)
=== RUN   TestCreateDeleteNamedSet
--- PASS: TestCreateDeleteNamedSet (0.00s)
=== RUN   TestDeleteElementNamedSet
--- PASS: TestDeleteElementNamedSet (0.00s)
=== RUN   TestGetRuleLookupVerdictImmediate
--- PASS: TestGetRuleLookupVerdictImmediate (0.00s)
=== RUN   TestConfigureNATRedirect
--- PASS: TestConfigureNATRedirect (0.00s)
=== RUN   TestConfigureJumpVerdict
--- PASS: TestConfigureJumpVerdict (0.00s)
=== RUN   TestConfigureReturnVerdict
--- PASS: TestConfigureReturnVerdict (0.00s)
=== RUN   TestConfigureRangePort
--- PASS: TestConfigureRangePort (0.00s)
=== RUN   TestConfigureRangeIPv4
--- PASS: TestConfigureRangeIPv4 (0.00s)
=== RUN   TestConfigureRangeIPv6
--- PASS: TestConfigureRangeIPv6 (0.00s)
=== RUN   TestSet4
--- PASS: TestSet4 (0.00s)
=== RUN   TestMasq
--- PASS: TestMasq (0.00s)
=== RUN   TestReject
--- PASS: TestReject (0.00s)
=== RUN   TestFib
--- PASS: TestFib (0.00s)
=== RUN   TestMap
--- PASS: TestMap (0.00s)
=== RUN   TestVmap
--- PASS: TestVmap (0.00s)
=== RUN   TestJHash
--- PASS: TestJHash (0.00s)
PASS
```
Versions:
```
root@ubuntu:~/go/src/github.com/google/nftables# uname -a
Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~/go/src/github.com/google/nftables# /usr/lib/go-1.10/bin/go version
go version go1.10.4 linux/amd64
```

Doesn't seem to be a kernel version, maybe one of the libs version ?

Libs:
```
root@ubuntu:~/go/src/github.com/google/nftables# apt list --installed | grep libmnl0
libmnl0/trusty,now 1.0.3-3ubuntu1 amd64 [installed]
root@ubuntu:~/go/src/github.com/google/nftables# apt list --installed | grep libmnl-dev
libmnl-dev/trusty,now 1.0.3-3ubuntu1 amd64 [installed]
```
+ Installed libnftnl from netfilter's git, current master branch.

**Comment by stapelberg** [comment]
Hm, that’s very strange. Library versions shouldn’t matter, as the `github.com/google/nftables` talks directly to the kernel (no C libraries involved).

I wonder if the travis kernel is patched, or whether any of their settings causes this behavior.

As per https://docs.travis-ci.com/user/environment-variables/#default-environment-variables, you can use `os.Getenv("TRAVIS") == "true"` to detect in a test whether it’s running on travis, and skip it to unblock this PR.

**Comment by Minaru** [comment]
I'll revert my debug commits and add this skip to the failing tests then !

**Pull request merged**
